### ISSUE TITLE
Sewing inaccuracy in Kirby Family

### ISSUE THREAD

**Issue by Kilicool64** [shonumi/gbe-plus#121]
I don't know if you're willing to look into this, given that this is an issue with a leaked game (don't know if it also happens somewhere in any of the sewing machine games that actually got released), but I tested some of the sewing patterns in Kirby Family. While most of them seem fine (there are some stray pixels, but it's possible the patterns simply aren't that accurate), there's one where something clearly goes wrong. Here's the full picture along with just the part that doesn't get "sewn" correctly. The sewing machine simulation first correctly "sews" Kirby's left shoe and mouth, but then it "sews" the right shoe without repositioning itself first.
![223793994124969860](https://user-images.githubusercontent.com/53983097/138120569-1b62f895-eba5-4f81-80b6-1467d0468302.png)
![2637245331946508462](https://user-images.githubusercontent.com/53983097/138120566-cc736fb9-68e4-44b3-b301-c46f251756d9.png)

**Comment by shonumi** [comment]
Okay, just a small update. The Kirby pattern works just fine with Patterns 1 and 3 on Kirby Family, but Pattern 2 is problematic, as you describe.

Good news is that this is the same issue I mentioned earlier with the kanji embroidery. I actually did fix it some time last year, but never committed it, so I guess it's time to actually do that now.

**Comment by Kilicool64** [comment]
Given that this issue is still open and hasn't been mentioned in the latest release notes, I take it you didn't get around to committing your fix yet?

**Comment by shonumi** [comment]
No, it was fixed quite a while ago, back in November -> beaa59467fa0745e17a588d7858a4ca658510587

I thought I'd closed this, but I guess I forgot to. Anyway, it's fixed in 1.6.
