### ISSUE TITLE
GBC game Star Wars Ep I - Obi-Wan's Adventures not playable

### ISSUE THREAD

**Issue by mkwong98** [shonumi/gbe-plus#133]
The emulator shows a white screen.

**Comment by shonumi** [comment]
Thanks for the heads up! This actually does work in GBE+ if you use the GBC Boot ROM. Without using it, however, it hangs on a white screen. Looks like some memory isn't initialized properly.

**Comment by shonumi** [comment]
Found the source of the problem. **0xFF55** was zero, which does not accurately reflect its post-boot value.

I'll have to add a bunch of GBC-specific post-boot values to the code soon.
