### ISSUE TITLE
Two missing Play-Yan Garage games thumbnails

### ISSUE THREAD

**Issue by GaussTek** [shonumi/gbe-plus#146]
Hello!

I managed to get working the Garage Games in Play-Yan, they work great, but there are two missing .BMP files for two games: TRIPLE and WAVE: https://www.nintendo.co.jp/n08/playan/garage/index.html

I haven't figured out how to make the .bmp thumbnail files, as when I try to do them, they just aren't recognized/the games won't load. Would be possible to add these two remaining BMP files so the games can be played?

Thank you, adding Play-Yan support was just amazing!!! <3

**Comment by shonumi** [comment]
Sure, I'll add them when I update the repo soon! I made the first 11 but kinda forgot to add the rest. Got caught up researching how the rest of the Play-Yan was supposed to work.

**Comment by shonumi** [comment]
Alright, the thumbnails for TRIPLE and WAVE should be up now. Tested them to make sure they unlocked the Garage Games and it seems fine.

**Comment by GaussTek** [comment]
Thank youuu! Just tested the remaining games and they seem fine on my end too!! 

Thanks a lot!! Never thought I would see the Garage games emulated one day haha.

**Comment by shonumi** [comment]
No problem. Hope you enjoyed my "art" for the thumbnails too!
