### ISSUE TITLE
Hardware rendering for replacement tiles?

### ISSUE THREAD

**Issue by ADormant** [shonumi/gbe-plus#15]
At present gbe+ uses only software rendering would it be possible to add hardware rendering for replacement tiles like HDNes is doing? I'd improve performance greatly.

**Comment by shonumi** [comment]
It can't. That's just not the nature of how it works in GBE+. HDNES, as far as I know, treats every tile like it's own texture, correct? That is not a good approach in my opinion.

On the GB through DS, everything is rendered per-scanline generally. It's possible to shift individual lines of a tile up or down, left or right on the next scanline (and many games do this). These are essentially mid-screen effects and with OpenGL textures, this is hard to translate. In the end, OpenGL textures would still need to be cut up in segments before blitting them to the screen, and those kind of operations still add up in terms of compute time. My main concern, however, is the code complexity it adds.

Furthermore certain palette colors between BG and OBJ tiles have different priorities in a number of situations on the GB/GBC (these priorities must apply to custom tiles as well).  Emulating this with OpenGL textures only is not possible as far as I know; you would still have to manually determine which pixel has priority through software. This must also be done in conjunction with the scanline issue mentioned above.

Overall, it's a bit more trouble than it's worth to implement, and there are easier targets for possible speed ups.

**Comment by ADormant** [comment]
@shonumi Per-pixel priority can be emulated with OpenGL.
https://github.com/Yabause/yabause/commit/b307da5386fd73950f1acb5c5824fb8c89e49e00
https://github.com/Yabause/yabause/commit/c6ffab78439de82e80cf1298b0747440c8f2a364
https://github.com/Yabause/yabause/commit/f04d3c5fcdf038e70848e0bac6140911d977fab4

**Comment by ADormant** [comment]
Per-pixel priority can be emulated with OpenGL.
https://github.com/Yabause/yabause/pull/22/files
https://github.com/Yabause/yabause/commit/b307da5386fd73950f1acb5c5824fb8c89e49e00
https://github.com/Yabause/yabause/commit/c6ffab78439de82e80cf1298b0747440c8f2a364
https://github.com/Yabause/yabause/commit/f04d3c5fcdf038e70848e0bac6140911d977fab4

**Comment by shonumi** [comment]
Those commits about the priority are for Yabause's software renderer (vidsoft.c). The OpenGL part (your first link) looks like it's doing something with sprites, but keep in mind, the GB and Saturn or two totally different systems. Not familiar with how the Saturn works, but 3D systems from that era could usually display "sprites" and flat-textured polygon, which makes the translation to an OpenGL texture easier. This is not the case for the Game Boy handhelds (though it can apply to the DS in some cases, depending on the game).

Anyway, the biggest problem is that a shader would have to know what the rest of the C++ variables in memory look like to determine all sorts of factors when rendering any given scanline (it needs to know the status of the emulated LCD and VRAM values, and the parameters regarding any replacement tiles). Shaders are their own programs that run on the GPU, but it has very little means to communicate with the rest of GBE+'s C++ code. Workarounds, as far as I know, would involve some use of CUDA or OpenCL, both of which are non-starters; I want to keep dependencies to a minimum (SDL, and optionally Qt for the GUI).

**Comment by ADormant** [comment]
I wonder if some sort of 2.5D effect in GBE is possible? https://www.reddit.com/r/emulation/comments/3u5u1c/emunity_new_unity3d_libretro_frontend_25d3d_gba/
@shonumi

**Comment by shonumi** [comment]
It's possible, but it still runs into the same issue when modifying certain MMIO registers mid-frame. E.g. it would be very difficult to emulate the "wavy screen" effects (see LoZ: Oracle of Ages/Season intro as Link wakes up) or any effects that rely on HBlank IRQs (the psuedo scaled/rotated BGs in MK: Super Circuit or F-Zero games).

Emunity is pretty cool (I was watching it before the author posted on Reddit this week) but I personally have no interest in going in that direction.

**Comment by ADormant** [comment]
@shonumi Vulkan has unified shader/OpenCL suport through Spir-V.

**Comment by ADormant** [comment]
@shonumi I have a question about your tile replacement method: Does graphics have to be processed only per-tile with this method or also per-line / pixel granularity like real console?

**Comment by ADormant** [comment]
Second question is how hard do you think it would be to add texture filtering to a DS emulator?
From what I heard  an NDS texture can be in 1 of 7 different formats, where only 3 out of the 7 formats has an alpha channel. . The texture's alpha channel could be 1-bit, 3-bit, 5-bit, or non-existent, and this difference can be on a per-texture basis. In addition, NDS has a per-polygon alpha that interacts with the texture alpha channel (whether the alpha channel is used or not), and this interaction can change depending on the polygon mode, which is also switched on a per-polygon basis. So texture corruption may happen when you create new levels of alpha during filtering.

**Comment by ADormant** [comment]
@shonumi 3. How do you plan to emulate geometry and lighting of DS, on GPU with shaders or traditionally on CPU like in Desmume? Emulating lighting on a cpu is easier but limits the ways in which you can modify and enhance it in an emulator.

**Comment by shonumi** [comment]
1) Graphics are handled on a per-scanline basis for DMG/GBC stuff. The GBA core handles things per-pixel, but this is really slow and is probably going to change one day to per-scanline. CGFX on the DMG/GBC are drawn whenever the emulator tries to try the original graphics but detects the presence of replacements.

2) I wouldn't know how hard it is, since I'm not even that far yet. It doesn't seem terribly difficult when you consider Desmume recently did texture filtering (e.g. applying pixel scaling algorithms to textures). I think the bigger issue is that most 2D scaling algorithms don't account for the alpha channel when determining new colors during interpolation.

3) Both will be used. I feel it's important to have a software renderer for accuracy, and  a hardware renderer for speed.

**Comment by ADormant** [comment]
> 3) Both will be used. I feel it's important to have a software renderer for accuracy, and  a hardware renderer for speed.

In Desmume when you use OpenGL backend geometry and lighting are still processed on a PC's CPU and just passed to GPU  to be renderered so you plan to do it all on GPU with hardware renderer?


> CGFX on the DMG/GBC are drawn whenever the emulator tries to draw the original graphics but detects the presence of replacements.

So replacements are done per-scanline too?


> Desmume recently did texture filtering (e.g. applying pixel scaling algorithms to textures).

xBRZ in Desmume is customized and apparently xBRZ texture upscaling is easier to implement for DS emulator than texture filtering like bilinear, trilinear and anisotropic.
By the way I recommend ddt as a texture filter.
https://github.com/libretro/common-shaders/tree/master/ddt
@shonumi

**Comment by shonumi** [comment]
I plan to do as much on the GPU as possible. I know the DS' graphical capabilities won't match desktop GPUs 1:1, but we'll cross that bridge when it comes. Hopefully OpenGL 3.3 or even 4.0 or Vulkan will provide the needed flexibility.

But yes, CGFX are done per-scanline. If you take a look at the DMG/GBC lcd.cpp, you'll see all kinds of functions for scanline rendering. Everything gets drawn to a screen buffer when entering HBlank, then the buffer is drawn to the user's screen when entering VBlank.

**Comment by shonumi** [comment]
Closing this since hardware rendering for CGFX is very unlikely in the future.
