### ISSUE TITLE
Post-processing shaders

### ISSUE THREAD

**Issue by ADormant** [shonumi/gbe-plus#22]
You are planning to implement post-processing are you not then I've some potentially useful links with good post-processing shaders and implementations.

https://github.com/Tinob/Ishiiruka/blob/master/Data/Sys/Shaders/Postprocessing/DolphinFX.glsl
https://github.com/Tinob/Ishiiruka/blob/master/Data/Sys/Shaders/Postprocessing/IshiirukaFX.glsl
https://github.com/PCSX2/pcsx2/blob/master/bin/shaders/GSdx.fx
https://github.com/Tinob/Ishiiruka/tree/master/Data/Sys/Shaders/Scaling
https://github.com/Tinob/Ishiiruka/wiki/Post-Processing-Shaders

https://github.com/dolphin-emu/dolphin/pull/3366/files
https://github.com/punesemu/puNES/commit/3a18faf4ad62c46906a5b26decbb6d43ae240ea8
https://github.com/Tinob/Ishiiruka/commit/b9b42db665b60b011901c88a469cd94b0798a336
https://github.com/Tinob/Ishiiruka/commit/3245921d431d7891a2e8cd12d2d3fcd73696392f
https://github.com/Tinob/Ishiiruka/commit/4822c371825e9720b6b3de595f70bfde66f7edf3
https://github.com/Tinob/Ishiiruka/commit/9dc73c0b166d09b550971bdb548f8568fe528ca4
https://github.com/Tinob/Ishiiruka/commit/3982da0834d517c53c95ab67c4685e697c2d2364
https://github.com/Tinob/Ishiiruka/commit/88cca4b74621448ca8675dd7441fb4a744573bac
https://github.com/Tinob/Ishiiruka/commit/3b278006da165424a779b19d118ad43c827f1cd7
https://github.com/Tinob/Ishiiruka/commit/649af162863e3ffd3295115cfa646cd659857102
https://github.com/Tinob/Ishiiruka/commit/d0cfeed1db93f1d41436535bf16de4618a24e9f9
https://github.com/Tinob/Ishiiruka/commit/827a4e8adc3207d436323108d770bfb390fb7bb7
https://github.com/Tinob/Ishiiruka/commit/f8e89a79a009335dde2714e71f69a28ea593e202
https://github.com/libretro/RetroArch/pull/2729/files
https://github.com/libretro/RetroArch/pull/2733/files
https://github.com/libretro/RetroArch/tree/master/gfx/drivers_shader

**Comment by ADormant** [comment]
https://github.com/Tinob/Ishiiruka/blob/master/Data/Sys/Shaders/Postprocessing/DolphinFX.glsl
https://github.com/Tinob/Ishiiruka/blob/master/Data/Sys/Shaders/Postprocessing/IshiirukaFX.glsl
https://github.com/Tinob/Ishiiruka/tree/master/Data/Sys/Shaders/Scaling
@shonumi

**Comment by ADormant** [comment]
https://github.com/PCSX2/pcsx2/blob/master/bin/shaders/GSdx.fx

**Comment by shonumi** [comment]
Thanks. I'll get to it eventually. It'll be more of a focus after the upcoming 1.0 release, so expect more on this stuff later this year.

**Comment by ADormant** [comment]
https://github.com/Tinob/Ishiiruka/commit/b9b42db665b60b011901c88a469cd94b0798a336
https://github.com/Tinob/Ishiiruka/commit/3245921d431d7891a2e8cd12d2d3fcd73696392f

**Comment by shonumi** [comment]
Technically, GLSL post-processing shaders were implemented as of f34106b2ca7185c28e24a8cdd1fb1c98b2beb950. Now it's just a matter of getting different types of shaders working. But shader support is now available, so I'm closing this (should have done this last month, but times flies).

**Comment by ADormant** [comment]
@shonumi could you make documentation explaining the shader system in GBE+ a la https://github.com/Tinob/Ishiiruka/wiki/Post-Processing-Shaders  .

**Comment by shonumi** [comment]
Yeah, it's on my TODO list for 1.1. Don't worry, everything will be explained in the manual and eventually on the wiki ;)
