### ISSUE TITLE
Too many replacements = garbage graphics

### ISSUE THREAD

**Issue by GregoryMcGregerson** [shonumi/gbe-plus#24]
It seems like the more tiles that are replaced the more trouble the emulator has rendering everything. Sometimes it won't even start and crashes instead. I'm running it with OpenGL on Windows 10. I had to compile from source 67874fdd7784e8c714899624e1864b82742e107e because the beta exe has similar errors as issue #23 .

![broken](https://cloud.githubusercontent.com/assets/8885274/14225044/356f8a5a-f869-11e5-9469-64adb0f57322.png)

Manifest and replacement tiles are [here](https://github.com/GregoryMcGregerson/GBE-Plus-Projects).

**Comment by shonumi** [comment]
As far as actually running on Windows, the RC1 should fix the dependency issues of the beta -> https://goo.gl/UqAqa8

I think this is a case of something that got broken in CGFX. It's not just Qt, the command-line SDL version segfaults too. I'm looking into this atm.

**Comment by shonumi** [comment]
Just a brief update, I can reproduce this when even just loaded 1 replacement (the Mushroom on the title screen for SML). Weird. Looks like an issue with how GBE+ is either loading or drawing them. The drawing code was changed to accommodate Qt, so the GUI could draw the result on-screen. I'll continue digging deeper.

**Comment by shonumi** [comment]
Update 2:

Dang, looks like HD rendering for replacements is totally messed up. Looks like it's been broken for quite a bit too. For what it's worth, 1:1 replacements work just fine and dandy, but even something as simple as 2:1 rendering ends up segfaulting. This is a pretty high priority bug.

**Comment by shonumi** [comment]
@GregoryMcGregerson - Does the latest commit work for you now? It seems to have fixed the graphics from your project (which look really nice btw).

**Comment by GregoryMcGregerson** [comment]
QT window doesn't even show up now. Must be a problem compiling on my end.

**Comment by GregoryMcGregerson** [comment]
Yes it works perfectly now!

**Comment by shonumi** [comment]
Cool beans! Keep up the great work on SML btw. I look forward to seeing more of your stuff.
