### ISSUE TITLE
[DMG] only unmasked INTs should wake from HALT

### ISSUE THREAD

**Issue by NasenSpray** [shonumi/gbe-plus#25]
see https://github.com/shonumi/gbe-plus/blob/master/src/dmg/z80.cpp#L219

> `else if(mem->memory_map[IF_FLAG] && mem->memory_map[IE_FLAG]) { halt = false; return false; }`

should be

> `else if(mem->memory_map[IF_FLAG] & mem->memory_map[IE_FLAG]) { halt = false; return false; }`

**Comment by shonumi** [comment]
Good catch! Dunno how that was missed all this time. Guess not a lot of games take advantage of this behavior.
