### ISSUE TITLE
[DMG] writes to REG_DIV should reset to 0

### ISSUE THREAD

**Issue by NasenSpray** [shonumi/gbe-plus#26]
this probably also needs to be changed then: https://github.com/shonumi/gbe-plus/blob/master/src/dmg/mmu.cpp#L1386

**Comment by NasenSpray** [comment]
You forget the HLE bios part here: https://github.com/shonumi/gbe-plus/blob/03a4b3d2529ff4f37d8cfdd31f98d0d8d59cd329/src/dmg/mmu.cpp#L1389
I think it should be `memory_map[REG_DIV] = 0xAF;`

**Comment by shonumi** [comment]
Thanks! That code `memory_map[REG_DIV] = 0xAF;` used to be the original code, but I changed it to use writes some time ago because the MMU has to perform certain actions when values are written, e.g. all the APU related NRxx registers.
