### ISSUE TITLE
Gameboy Advance bugs

### ISSUE THREAD

**Issue by benderscruffy** [shonumi/gbe-plus#32]
2 Great Games! - Pac-Man World + Ms. Pac-Man - Maze Madness (USA)
emulator closes down when you choose your game

007 - NightFire (USA, Europe) (En,Fr,De)
no music or sound fx and during gameplay bottom of the screen is glitchy and flashing

007 - Everything or Nothing (USA, Europe) (En,Fr,De)
no music or sound fx

**Comment by benderscruffy** [comment]
CRAZY RACER 3D
background is all black
![43701750385720](https://cloud.githubusercontent.com/assets/2696404/14593582/c80de652-055e-11e6-86ef-e4e014ae941d.png)

BITS2008 (GBA Demo)
nothing but a white screen
http://thebitsclub.tripod.com/demo/BITS2008-GBA-20130711.ZIP

**Comment by shonumi** [comment]
Just FYI, you're going to find **a lot** of GBA bugs because the GBA core is very, very incomplete. So good luck documented all that stuff ;)

Again, thanks for the reports, screenshots are awesome too!

**Comment by benderscruffy** [comment]
ok thanks for the heads up
i wont look for any more bugs

**Comment by benderscruffy01** [comment]
using 1.3
all the bugs are still present

**Comment by benderscruffy01** [comment]
Classic NES series
all of them nothing but a black screen

**Comment by benderscruffy01** [comment]
Hamtaro - Ham-Ham Heartbreak (USA)
freezes up after you confirm your names
![hamster](https://user-images.githubusercontent.com/48821663/55703779-20084b80-5a0d-11e9-869b-b6a08bfa7367.PNG)
