### ISSUE TITLE
[GBC] "Densha de Go! 2" Unkown Opcode 0xD3

### ISSUE THREAD

**Issue by CaptainCaffeine** [shonumi/gbe-plus#45]
"Densha de Go! 2" crashes almost immediately in GBE+ with `Error - Unknown Opcode : 0xd3`. This game is the only official cart to use more than 256 ROM banks, so the issue might be in the MBC5 emulation.

**Comment by shonumi** [comment]
Problem was only using u8 (0-255) when reading in banks from the ROM. So, the second half of the banks overwrote the 1st half. GBE+ kept messing up even though it was reading stuff from Bank 6. Subtle error, but it's fixed now :D
