### ISSUE TITLE
No shortcut for muting sound

### ISSUE THREAD

**Issue by ficion** [shonumi/gbe-plus#47]
![image](https://cloud.githubusercontent.com/assets/938873/24677295/b72013d4-195c-11e7-82ac-4d1284b82df7.png)
You can also open two Setting windows at the same time, which I don't think is very ideal.

**Comment by shonumi** [comment]
GBE+ already has a hotkey for muting sound (defaults to the "M" key). This works for both SDL and Qt. It's not listed in the Qt GUI, but it's still functional. Hotkeys can only be configured by the .ini file at the moment, until some more work in done on a configuration dialog.

As for opening two settings windows, I'm unable to reproduce this. That screenshot you provided isn't from GBE+. That's from different program. Are you sure you reported this issue to the right project?

**Comment by ficion** [comment]
This is so embarrassing. I'm so sorry, I mixed up and I just noticed!
