### ISSUE TITLE
Windows binary?

### ISSUE THREAD

**Issue by ADormant** [shonumi/gbe-plus#49]
It's been a very long time since the last Windows release. Will Windows still be supported and if so any idea when the Windows version is going to be released?

**Comment by shonumi** [comment]
Windows support was never "dropped". Building stuff on Windows just isn't as friendly for me as it is on Linux. For 1.1, I couldn't push a binary in time for the stable release.

Ideally, getting a build-bot setup and making the complete transition to Qt5 are requirements for 1.2.

**Comment by frozenLake** [comment]
Its been over half a year: could you see about throwing up a build?

**Comment by shonumi** [comment]
When it's done and ready. Check back April 1st, 2018 (when 1.2 comes out). Point-releases are the only time I do binaries. Had to skip 1.1 due to issues on Windows.

**Comment by shonumi** [comment]
1.2 is out.
