### ISSUE TITLE
Add ability to play GB games at GBC double speed

### ISSUE THREAD

**Issue by RushJet1** [shonumi/gbe-plus#52]
I was just wondering if you could enable this functionality- would fix a lot of slowdown in older GB games.  BGB has this as an option in its debugger.

**Comment by shonumi** [comment]
Sure! I'll go even further and add an overclocking option to do 4x the DMG speed, and an even faster speed that treats all instructions as taking only 1 clock cycle. I fiddled around with this for Face Ball 2000 a long time ago, and it turns it into a decent portable FPS.

**Comment by shonumi** [comment]
Added this feature as of 18cf3c8f17c401220c5942fc755476bb3c90656a. The feature allows the CPU's speed to run at 1x, 2x, 4x, or 8x. Currently only available for DMG, GBC, and SGB games. Gets rid of the lag in MMV (2x and above) and makes Face Ball 2000 run pretty smooth at 8x.
