### ISSUE TITLE
PDF mistakenly claims that 1.1 has a release.

### ISSUE THREAD

**Issue by frozenLake** [shonumi/gbe-plus#57]
This is in the first sentence of 2.1 Obtaining, Compiling, & Installing GBE+.

This /could/ be fixed by making a late build of what everything was at 1.1, but well, chances are that you would just change the PDF to point at 1.0 instead.

**Comment by shonumi** [comment]
1.2 is less than 2 months away, so it's pointless to make a 1.1 release right now (especially since 1.1 needs a bunch of ugly hacks to work on Windows, as opposed to what 1.2 will be). All the info in the PDF only gets updated once a year with every release, so it'll get fixed in a bit.

**Comment by shonumi** [comment]
Fixed since the new PDF points to 1.2 which does have a Windows build :)
