### ISSUE TITLE
CGFX Tiles not always loaded correctly in Pokémon TCG

### ISSUE THREAD

**Issue by JappaWakka** [shonumi/gbe-plus#58]
When changing graphics in Pokémon TCG and then navigating through the interface, graphics often do not load or unload. See screenshots attached.
![bugscreen1](https://user-images.githubusercontent.com/31563291/38202923-c2fb363e-369d-11e8-8fee-795322ce7512.png)
![bugscreen2](https://user-images.githubusercontent.com/31563291/38202922-c2d18406-369d-11e8-8d30-ff5343be9c08.png)

**Comment by shonumi** [comment]
Okay, I think I see what might be going on here. I believe it's something specific to how GBC CGFX are handled. Something similar happens with Shantae too, probably other games as well. Now that I have two test cases, I can narrow it down. Thanks for the report, will look into this shortly.

**Comment by JappaWakka** [comment]
Same happened with Pokémon TCG 2 (english fan translation), which also has performance problems when custom graphics are on.

**Comment by shonumi** [comment]
This issue should be fixed now. Mind testing this build just to confirm?

https://mega.nz/#!roNXxRjA!Moe_W6hT9xaSnhg2rTpuAB9tMS-8bRUk-CBmI3ejrHA

About the performance problems in TCG 2, CGFX can get very demanding under certain circumstances (some games constantly force GBE+ to recalculate hashes, even if no graphics are replaced). Additionally, the larger your custom graphics are, the more demanding it will be for GBE+ to draw them. So there are situations where CGFX can bring even beefy systems to their knees. A few scenarios such as hash look-ups can be improved for better speed, but other cases might have unavoidable slowdowns for the time being.

**Comment by JappaWakka** [comment]
YES! You're amazing! No more background glitches and for some reason performance has improved in Pokemon TCG 2!!! I love you! Thank you so much!

**Comment by JappaWakka** [comment]
Oh nevermind, the performance improvement was random

**Comment by shonumi** [comment]
Yeah, performance is going to be a complex issue, depending on a host of different factors. Hopefully using multiple CPU cores can help in some instances (hashing and hash lookup). Definitely something I'll address in the future. For now I'll close this since CGFX doesn't glitch up the graphics any more. Thanks for testing the dev build!
