### ISSUE TITLE
[GBC] Both Zelda Oracle games freeze after displaying logos.

### ISSUE THREAD

**Issue by frozenLake** [shonumi/gbe-plus#59]
I have tried this with multiple versions of the two games, and all have frozen in the same place. Running through another emulator, in this case, VBA, results in the game functioning fine.

**Comment by shonumi** [comment]
Alright, I'll look into it soon. I might have to do some bisecting to see what change caused the freeze (I was playing Oracle of Seasons last year on GBE+). Hopefully it's something obvious.

**Comment by shonumi** [comment]
Managed to fix this. It was some of the Game Boy's  sound registers not properly setting their ON/OFF status bits. Apparently the music engine is quite picky in the LoZ Oracle games.
