### ISSUE TITLE
CGFX Corruption (Pokemon Yellow)

### ISSUE THREAD

**Issue by frozenLake** [shonumi/gbe-plus#60]
I've only replaced one tile, the manifest itself being literally
`['Dump\BG\Tile_Reds_House_Floor.bmp':Tile_Reds_House_Floor:0]
[0qk0_8004002001002w04g0880040:Tile_Reds_House_Floor_0:20:0:0]`

I have provided some visual examples, as well. I don't know what could be causing this. The visual corruption seemed to be consistent at first, but now does not appear to be the case. It is affected whenever the player interacts with an object or talks with someone, but it still exists outside of that.

![image](https://user-images.githubusercontent.com/9343490/38332557-e3d856b4-381b-11e8-8a43-6c15b19c4374.png)

![image](https://user-images.githubusercontent.com/9343490/38332652-1fb3f3c8-381c-11e8-9017-2274d634fb1d.png)

![image](https://user-images.githubusercontent.com/9343490/38332662-269bc274-381c-11e8-9082-296de7379750.png)

**Comment by frozenLake** [comment]
A recent discovery has been made: viewing the menu in multiple places makes it note that the tiles are shifted to where they would have been "on screen" when the room is initially loaded.

**Comment by shonumi** [comment]
You're playing in GBC mode right? If so, it's the exact same issue as TCG, so this is a duplicate.

**Comment by shonumi** [comment]
I should also mention that there's nothing wrong on your end. This is GBE+ not updating hashes in a timely fashion. Just need to figure out where the GBC updates are messed up. I think you should be able to trigger similar problems by enabling  CGFX even without a manifest.

**Comment by frozenLake** [comment]
Yes, this is in GBC mode. I guess that I should try to run it in regular gameboy mode from here on out.

**Comment by frozenLake** [comment]
also, an unrelated bug with yellow is that pikachu's voice clip is non-existent when playing through gbe+. Not sure if I should make a full on issue for that.

**Comment by shonumi** [comment]
DMG mode should be fine for updating hashes. GBC mode is the one with the issues, and Issue #59 deals with that for future reference.

I'll make an issue for the voice later, since the real problem is broader than just Pokemon Yellow (Army Men 2, Cannon Fodder, Tarzan, Chee Chai Alien, Sakura Taisen GB, the list goes on).

**Comment by shonumi** [comment]
This issue should be fixed now. Mind testing this build just to confirm?

https://mega.nz/#!roNXxRjA!Moe_W6hT9xaSnhg2rTpuAB9tMS-8bRUk-CBmI3ejrHA

**Comment by frozenLake** [comment]
That fixes it.

**Comment by shonumi** [comment]
Thanks for the feedback! Marking this issue as closed in that case.
