### ISSUE TITLE
Sprite rotation is buggy when dealing with high resolution CGFX.

### ISSUE THREAD

**Issue by frozenLake** [shonumi/gbe-plus#64]
![image](https://user-images.githubusercontent.com/9343490/38787934-89dbdab2-40f6-11e8-9b7c-03cf17c70e68.png)
This is the example. I don't think I need to describe further. it appears that the inside of the "pixels" isn't affected by the rotation, so you have 2x2 sections acting as if they had their original rotation.

**Comment by shonumi** [comment]
Let me see what you're working with (manifest + custom graphics), then I'll see what's going on.

**Comment by shonumi** [comment]
Thanks! I think I've located the problem. It's only vertical flipping if I'm testing it correctly. Looks like some code wasn't designed to handle 8x16 OBJs properly in these cases. Will check if it affects 8x8 OBJs too.

**Comment by shonumi** [comment]
Should be fixed now. Tested it myself with the graphics + manifest you provided. Double-check with this development build, if you wouldn't mind:

https://drive.google.com/file/d/1j8xiS5Ou_Y3-YXKwCm66HoLVUb3tCHbG/view?usp=sharing

**Comment by frozenLake** [comment]
I can confirm that this works. Sorry for not responding sooner.

**Comment by shonumi** [comment]
No problem. Thanks for testing!
