### ISSUE TITLE
.gb files do not show up in the recent files list.

### ISSUE THREAD

**Issue by frozenLake** [shonumi/gbe-plus#66]
I don't really know why this happens, but it should be a simple fix?

Edit: okay apparently its original gameboy games in general, since renaming the extension didn't work.

**Comment by shonumi** [comment]
Had a bit of a delay getting a nightly build up, but I think it fixed this a few days ago. GBE+ now saves the .ini file immediately after opening a file. Make sure GBE+ can actually read/write to the .ini file though. Anyway, here's the latest dev build to test:

https://mega.nz/#!65NT2JBC!JErlbvJYNL7x2nNo3xpsAacBzNjfWAvITACVgqFBjKM

**Comment by shonumi** [comment]
Like I said, make sure you can read/write the .ini file. For example, when you change something like the screen scale, then exit GBE+, it should save the screen scale when you open GBE+ again. If that doesn't happen, that means GBE+ can't access the .ini file, and therefore it can't save any changes you make to any settings (and the recent file list is part of the settings).

Make sure the .ini file is right next to the .exe file.

**Comment by shonumi** [comment]
Additionally, make sure the title does **not** have an apostrophe (aka a single quote). That messes up how GBE+ parses .ini files.

**Comment by frozenLake** [comment]
Honestly, a way to fix this maybe would be adding an escape character to the formatting of the ini?

**Comment by shonumi** [comment]
Should be fixed in this build: https://mega.nz/#!C00RyS5S!JCcDg4boib9lDmA5C-RmuHawHDinGOpwcR_CIqsRUOI

**Comment by frozenLake** [comment]
Can confirm this solves the problem.
