### ISSUE TITLE
CGFX cause a huge amount of lag.

### ISSUE THREAD

**Issue by frozenLake** [shonumi/gbe-plus#70]
I was attempting to colorize Megaman V. However, after reaching a certain point, adding any more entries for CGFX just causes a huge amount of lag. This lag is not caused by file count, but by the number of tiles listed in the manifest. I have attached a zip containing my present manifest and replacement tiles.
[DumpMegaman.zip](https://github.com/shonumi/gbe-plus/files/1968960/DumpMegaman.zip)

I don't know how much its causing it to slow down by, since there isn't an option to display an FPS counter. Perhaps that could be added, soon?

**Comment by frozenLake** [comment]
Honestly, EXT_VRAM_ADDR never did anything in regards to keeping tiles in their own place, since they affect things that aren't in that address anyway.

**Comment by shonumi** [comment]
Should be fixed in this build: https://mega.nz/#!C00RyS5S!JCcDg4boib9lDmA5C-RmuHawHDinGOpwcR_CIqsRUOI

**Comment by frozenLake** [comment]
This cut down on lag significantly.

I'm not sure how much CGFX I would need to cause a dip in frame rate, now. Probably in the thousands.
