### ISSUE TITLE
ARM conditional code crash, LOZ Minish Cap

### ISSUE THREAD

**Issue by saschasnowstorm** [shonumi/gbe-plus#76]
![error](https://user-images.githubusercontent.com/39711759/40628595-b8ab2e38-627a-11e8-9cac-e45e15931045.JPG)

In the cylone room of the Dark Castle late in game, after about 2 seconds the emulator hangs and crashes. 

"CPU::Warning: ARM Instruction uses reserved conditional code NV
SWI::Error - Unknown Bios function 0xff
CPU::Warning: ARM Instruction uses reserved conditional code NV
SWI::Register RAM Reset
SWI::Error - Unknown Bios function 0x7f"

**Comment by saschasnowstorm** [comment]
![errorlocation](https://user-images.githubusercontent.com/39711759/40628996-36bfbee0-627d-11e8-9159-1de31dcb93ec.JPG)
Location

**Comment by shonumi** [comment]
Can you send me your save? I'll take a look.

**Comment by saschasnowstorm** [comment]
Of Course

Save - https://drive.google.com/open?id=1kpPLveSoYXKtJZogV64Yyxf5TsbzDi7S
Savestate 1 outside the room - https://drive.google.com/open?id=1sNgUxWzzzIEEgOTDau3P_tm_EyOUNkFc

**Comment by shonumi** [comment]
Thanks! I'll get back to you in a while. Hopefully it's something simple. Wonder if it might be more anti-piracy measures in the game.

**Comment by shonumi** [comment]
This should be fixed now. A basic build-bot is up and running, and the latest builds should be available on mega.nz from now on -> https://mega.nz/#F!GhcQ1QYB!L5_8qN_S0gqYE-oCCa9mJQ
