### ISSUE TITLE
Custom Tiles don't get flipped properly.

### ISSUE THREAD

**Issue by frozenLake** [shonumi/gbe-plus#78]
![102833798161999](https://user-images.githubusercontent.com/9343490/41237586-851598b2-6d59-11e8-95dd-f0c7537ccd19.png)

Sprites still function though, so this is BG exclusive.

**Comment by shonumi** [comment]
This should be fixed now. A basic build-bot is up and running, and the latest builds should be available on mega.nz from now on -> https://mega.nz/#F!GhcQ1QYB!L5_8qN_S0gqYE-oCCa9mJQ

**Comment by frozenLake** [comment]
Unfortunately, this doesn't seem to fix it.

**Comment by shonumi** [comment]
I tested it yesterday and verified it twice. Are you sure? Send me any suspect files

**Comment by frozenLake** [comment]
![14815950601538](https://user-images.githubusercontent.com/9343490/41304788-bd9659c8-6e36-11e8-812d-5cc8d55c72d2.png)
[manifest.txt](https://github.com/shonumi/gbe-plus/files/2094966/manifest.txt)
![lowerrightgrass](https://user-images.githubusercontent.com/9343490/41304831-daad48fa-6e36-11e8-88c9-9af0e36e1cd9.png)

For the sake of showcasing the bug, I have provided the minimal manifest and tile replacement that shows this bug. Please use with Oracle of Ages.

**Comment by frozenLake** [comment]
![489319554848508](https://user-images.githubusercontent.com/9343490/41305122-8f68c0bc-6e37-11e8-9904-cd9a2a44a7f3.png)
Did a quick test, making sure that the tiles replaced didn't have any flipping when dumped. While vertical flipping works, horizontal does not. Plus, flipping is not considered when dumping tiles, so that is a secondary bug.

**Comment by shonumi** [comment]
Flipping isn't considered when dumping because the tile data is the same. It's just a flag in VRAM that flips it, and that's not necessary for the purposes of CGFX. CGFX reads the flag in real time and draws accordingly. Users have to be aware of any flipping to avoid dumping duplicates though.

I specifically tested horizontal flipping with the sign and it works. I'll have to see what's going on with the grass.

**Comment by shonumi** [comment]
Should definitely be fixed now. Buildbot was kind of broken for the past few days (wouldn't decrypt files on MEGA after uploading them), but that's been resolved. The link above is still good, so use the latest file available.

**Comment by frozenLake** [comment]
![276634654740240](https://user-images.githubusercontent.com/9343490/41422106-da56c466-6fbd-11e8-8298-c8ed0bc3ad3d.png)
What the hell happened here?!

**Comment by shonumi** [comment]
Again, if you have issues, I **need** to see the files you're working with.

**Comment by frozenLake** [comment]
[f7f5cc42f3dd485494c2f051d70391dea6eb871b.zip](https://github.com/shonumi/gbe-plus/files/2103327/f7f5cc42f3dd485494c2f051d70391dea6eb871b.zip)
Sending over the build and Dump folder, in order to maximize information sent. Oracle of Ages is not included, for obvious reasons.

**Comment by frozenLake** [comment]
I can confirm that https://github.com/shonumi/gbe-plus/commit/d72d0f63dc0cdde13224a5daeffba7145237993c fixes both the old, and the new problem.
