### ISSUE TITLE
Local netplay seems not to work (Windows binary)

### ISSUE THREAD

**Issue by Plumakeem** [shonumi/gbe-plus#81]
Hello,

somehow I can't enable the local netplay feature via **GB Link Cable** neither under **Windows 7 64bit** nor **XP 32bit** (**gbe-plus 1.2**). 

I followed the manual to set the ports matching each other in reverse (server a = port b, port a = server b) but when I enable the netplay on both instances they both time out. I'm not sure if the local netplay is intended to run from one or two different local copies, however both methods fail as well as variations in selecting the same rom twice or copies. I also tested to use the local ip 192.168.*.* instead of 127.0.0.1.

Every time I receive several times
`SIO::Netplay is waiting to establish remote connection...`
and then finally
`SIO::No netplay connection established`

Can someone confirm this?

Thank you for your help.

**Comment by shonumi** [comment]
The binaries aren't built with netplay support. They're missing SDL2Net. The buildbot isn't set up to use it currently. You can build it from source yourself however. If you can wait until later this month, it should be added.

This really isn't an "issue" per se, so I'm not going to add any tags to it, and the buildbot is separate from the actual GBE+ codebase.

**Comment by Plumakeem** [comment]
Ok I built it myself and its working now. I was just confused that it didn't work as I hadn't found any information that the build was without net support. 

Thanks for this awesome project and the interesting detail articles! Especially the IR article was very interesting and I hope the HuC-1 protocol mystery will be solved someday.

**Comment by Mushman** [comment]
Is netplay now compiled into current builds? I have the exact same issue in 1.3.

I was also unable to compile a build myself, despite spending hours upon hours trying. I admit that I struggle immensely building projects from source, and the closest I was about to get was past the CMake stage but having Visual Studio unable to find GLEW under the `common` project, plus almost four thousand errors due to unresolved SDL symbols...

**Comment by shonumi** [comment]
It's not enabled in 1.3 or in any of the available development builds. I could get it set up in a few days though. I'll ping you when it's up.

**Comment by Mushman** [comment]
Thank you very much for sorting it out yourself. I apologise I wasn't able to compile one on my own.
