### ISSUE TITLE
GLES support

### ISSUE THREAD

**Issue by hadess** [shonumi/gbe-plus#89]
Trying to get GBE+ merged into Flathub for Linux users, but I'm afraid that I couldn't get it to compile on ARM, as there's no "full-fat GL" there, just GLES.

See https://github.com/flathub/flathub/pull/753

```
In file included from /usr/include/SDL2/SDL_opengl.h:2105:0,
                 from src/./gba/lcd.h:13,
                 from src/./gba/arm7.h:22,
                 from src/./gba/core.h:20,
                 from /run/build/gbe-plus/src/qt/gbe_plus_qt_automoc.dir/../main_menu.h:28,
                 from /run/build/gbe-plus/src/qt/gbe_plus_qt_automoc.dir/moc_main_menu_3PF3EQY72JI6CZ.cpp:9,
                 from /run/build/gbe-plus/src/qt/gbe_plus_qt_automoc.cpp:8:
/usr/include/SDL2/SDL_opengl_glext.h:472:19: error: conflicting declaration ‘typedef ptrdiff_t GLsizeiptr’
 typedef ptrdiff_t GLsizeiptr;
                   ^~~~~~~~~~
In file included from /usr/include/QtGui/qopengl.h:105:0,
                 from /usr/include/QtGui/QtGui:45,
                 from /usr/include/QtWidgets/QtWidgetsDepends:4,
                 from /usr/include/QtWidgets/QtWidgets:3,
                 from /run/build/gbe-plus/src/qt/gbe_plus_qt_automoc.dir/../cgfx.h:19,
                 from /run/build/gbe-plus/src/qt/gbe_plus_qt_automoc.dir/moc_cgfx_JJEMC4PQ6NT5VF.cpp:9,
                 from /run/build/gbe-plus/src/qt/gbe_plus_qt_automoc.cpp:2:
/usr/include/GLES3/gl32.h:77:25: note: previous declaration as ‘typedef khronos_ssize_t GLsizeiptr’
 typedef khronos_ssize_t GLsizeiptr;
                         ^~~~~~~~~~
```

[gbe-plus-arm-build-log.txt](https://github.com/shonumi/gbe-plus/files/2917034/gbe-plus-arm-build-log.txt)

**Comment by shonumi** [comment]
Unfortunately I'm not interested in supporting GLES. I do plan on making OpenGL an optional requirement, so it can be disabled if necessary during compilation. That way it defaults to the software renderer and would build on anything that at a bare minimum supports SDL2.

**Comment by hadess** [comment]
Anything that would make it possible to run on 32-bit ARM would be nice, although I'm also fine with you not supporting it. 32-bit ARM probably means older Raspberry Pis or SoCs of a similar age, so it would probably be fine to not support those if GBE+ is not going to run adequately.

**Comment by hadess** [comment]
ARM 32-bit support was removed from Flathub, so I don't have any particular interest in GLES support anymore.
