### ISSUE TITLE
[GBA] Golden Sun: The Lost Age will not boot

### ISSUE THREAD

**Issue by shonumi** [shonumi/gbe-plus#9]
The game simply shows a black screen. The first Golden Sun boots just fine.

**Comment by shonumi** [comment]
GBE+ Endlessly prints the following:

`Out of bounds write : 0xe25ef01c`
`Out of bounds write : 0xe25ef01d`
`Out of bounds write : 0xe25ef01e`
`Out of bounds write : 0xe25ef01f`

Looks like it's trying to write a word somewhere, but it's either not the right word or the address is wrong (or both). Some debugging should uncover where that value comes from.

**Comment by shonumi** [comment]
Curiously, I think the trouble might be coming from MSR. It manually changes the Mode bits in CPSR. It seems to manually switch from SYS and IRQ modes. Given that this game was made by Camelot, who have been known to do crazy, custom code, I don't doubt that this is one of their old tricks.

**Comment by shonumi** [comment]
From GBATEK, about THUMB.19 -> "Using only the 2nd half of BL as "BL LR+imm" is possible (for example, Mario Golf Advance Tour for GBA uses opcode F800h as "BL LR+0")"

During IRQ handling, GBE+ jumps to a wrong address because it encounters this Long Branch instruction, which seems to be the cause it to not boot at all. But I have no idea what the rules are for only using only 1 half of the 32-bit instruction. This is Camelot at its finest! Using obscure hardware behavior...

@endrift - Have you done any research into this matter? I'm going to code a specific exception for the F800h opcode, but if you've found out more, I'd love to look into it :)

**Comment by endrift** [comment]
I never ran into this issue as I always implemented bl as two instructions. The ARM ISA manual specifies which operations take place when, even.

**Comment by shonumi** [comment]
That's what I'm doing now, breaking down BL as two instructions. The thing is, my implementation always expect BL to operate as if all 32-bits of the opcode are necessary. As GBATEK describes, however, there are cases where you only take the 1st instruction (i.e. ignore the last 16-bits).

I suppose the larger issue here is the I always assume the 2nd  instruction is a proper THUMB.19 instruction. I don't do any verification. In this case, I'll have to abort processing the second instruction if it isn't actually encoded as THUMB.19.
