### ISSUE TITLE
Gunstar Super Heroes (USA) black screen

### ISSUE THREAD

**Issue by benderscruffy01** [shonumi/gbe-plus#96]
using 1.3
during gameplay go out of the first screen and after that nothing but a black scrren

**Comment by shonumi** [comment]
Fixed as of 6172656737d3dd8ddff9e7f6f570cacc53029475.

Some slight BG-OBJ priority fighting happens in the rotating jet-level (2nd level), but the game's playable now past the first screen.

**Comment by benderscruffy01** [comment]
did you want to open a new issue about the 2nd level ???

**Comment by shonumi** [comment]
No, it's pretty minor, and I'll just add a note about it in #32. I have a couple others to add to that list too.

I expect to fix a lot of graphical bugs when I completely rewrite the LCD rendering code later.
